{% set name = "opentelemetry-instrumentation-aiohttp-client" %}
{% set version = "0.40b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_aiohttp_client-{{ version }}.tar.gz
  sha256: 4de0a72b922d391183d00e2a1cc32e52b88dd2a6c77311b166e566b125b19943

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - aiohttp ~=3.0
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.40b0
    - opentelemetry-semantic-conventions ==0.40b0
    - opentelemetry-util-http ==0.40b0
    - wrapt <2.0.0,>=1.0.0
    # - opentelemetry-instrumentation-aiohttp-client 
    # - opentelemetry-instrumentation-aiohttp-client 
    # - opentelemetry-instrumentation-aiohttp-client 
    # - opentelemetry-instrumentation-aiohttp-client 
    # - http-server-mock 

test:
  imports:
    - opentelemetry.instrumentation.aiohttp_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-aiohttp-client
  summary: OpenTelemetry aiohttp client instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - twoodwark
    - mariusvniekerk
